[package]
name = "rocket_http"
version = "0.1.0"
authors = ["Shanon McQuay <shanonmcquay@gmail.com>"]

[dependencies]
rocket = "0.4.0"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["serve", "handlebars_templates"]
