[package]
name = "rocket_http"
version = "0.1.0"
authors = ["Shanon McQuay <shanonmcquay@gmail.com>"]

[dependencies]
rocket = "0.4.0-rc.1"

[dependencies.rocket_contrib]
version = "0.4.0-rc.1"
default-features = false
features = ["serve"]
